name = "cloudia-api"
main = "src/index.ts"
compatibility_date = "2025-12-01"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[[d1_databases]]
binding = "DB"
database_name = "cloudia-db"
database_id = "46899f2e-3753-4465-bc78-c2f6e6cc36b5"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "cloudia-media"
